# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coolapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coolapp.Film')),
            ],
        ),
    ]
