# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolapp', '0002_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('wind', models.IntegerField()),
                ('temp_min', models.IntegerField()),
                ('temp_max', models.IntegerField()),
            ],
        ),
    ]
